---
development:
  cloud_name: chronosphere111
  api_key: '258292147443314'
  api_secret: Ivrk_I40FjREMz28rf6XkLm61Ik
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: chronosphere111
  api_key: '258292147443314'
  api_secret: Ivrk_I40FjREMz28rf6XkLm61Ik
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: chronosphere111
  api_key: '258292147443314'
  api_secret: Ivrk_I40FjREMz28rf6XkLm61Ik
  enhance_image_tag: true
  static_image_support: false
